name: Install Clang
description: Install Clang
inputs:
  architecture:
    required: true
    type: string
  al_version:
    required: true
    type: string
runs:
  using: composite
  steps:
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/clang/disable-sysroots-aarch64.patch"
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'arm64' }}
    - run: git apply "${GITHUB_WORKSPACE}/assets/patches/clang/disable-sysroots-x86.patch"
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'x86' }}
    - run: ./tools/clang/scripts/build.py --without-android --without-fuchsia --use-system-cmake --host-cc /bin/clang --host-cxx /bin/clang++ --with-ml-inliner-model=''
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'arm64' }}
    - run: ./tools/clang/scripts/build.py --without-android --without-fuchsia --with-ml-inliner-model=''
      shell: bash
      working-directory: /home/runner/src
      if: ${{ inputs.architecture == 'x86' }}
